# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language (English)
en:
  languageCode: en-us
  contentDir: content/en
  title: taeyunahn's CV
  params:
    description: tahn's CV site.
  menus:
    main:
      - name: Introduction
        url: /
        weight: 10
      - name: Projects
        url: projects/
        weight: 11
      - name: Skills
        url: skills/
        weight: 12
      - name: Other History
        url: others/
        weight: 13
      - name: Posts
        url: posts/
        weight: 20
      - name: Hobbies
        url: hobbies/
        weight: 30

# Korean language configuration
ko:
  languageCode: ko
  contentDir: content/ko
  title: 안태윤 CV
  params:
    description: 안태윤의 이력서 사이트입니다.
  menus:
    main:
      - name: 소개
        url: /
        weight: 10
      - name: 프로젝트
        url: /#projects
        weight: 11
      - name: 스킬
        url: /#skills
        weight: 12
      - name: 기타 이력
        url: /#others
        weight: 13
      - name: 포스트
        url: /#posts
        weight: 20
      - name: 취미
        url: /#hobbies
        weight: 30
