# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  title: taeyunahn's CV
  params:
    description: tahn's CV site.
  menus:
    main:
    - name: Introduction
      url: /
      weight: 10
    - name: Experience
      url: experience/
      weight: 20
    - identifier: projects
      name: Projects
      weight: 30
    - name: Backend
      parent: projects
      url: backend/
      weight: 31
    - name: Frontend
      parent: projects
      url: frontend/
      weight: 32
    - name: Other
      parent: projects
      url: other/
      weight: 33
    - name: Skills
      url: skills/
      weight: 40
    - name: Contact
      url: contact/
      weight: 50

ko:
  languageCode: ko
  contentDir: content/ko
  title: 안태윤 CV
  params:
    description: 이력서 url 입니다.
